version: "3.9"
services:
  #Service api_langue
  api_langue:
    #Permet de crée une image depuis le dockerfile
    build:
      context: ./api_langue/
      dockerfile: Dockerfile
    #Nom du container
    container_name: api_langue
    #Définis le réseau
    #networks:
    #  - app
    #Permet de mettre les variable d'environnement dans un fichier et ainsi pour poster le docker-compose sans donnée compromettante
    env_file: .env
    labels:
      #- traefik.http.routers.web-api.rule=Host(`trdad-api.dan.ynovaix.com`)
      - traefik.enable=true
  #Service api_proxy
  api_proxy:
    build:
      context: ./api_proxy/
      dockerfile: Dockerfile
    #Nom du container
    container_name: api_proxy
    #Expose le port 8080 de l'host vers le 80 du container
    # ports:
    #  - "5002:5002"
    #Execute d'abord l'api le proxy
    depends_on:
      - api_langue
    #Définis le réseau
    #network_mode: host
    #networks:
    #  - app
      #- traefik-public
    #Permet de mettre les variable d'environnement
    environment:
    - ISSUER_BASE_URL=${ISSUER_BASE_URL}
    - AUDIENCE=${AUDIENCE}
    - URL_API_PYTHON=api_langue:5000
    - MAX_REQUEST=50
    - TIME_LIMITE=1
    labels:
      - traefik.http.routers.api-proxy-livraison-traduction.rule=Host(`trad-api.dan.ynovaix.com`)
      - traefik.enable=true
      #- traefik.http.routers.api-proxy-livraison-traduction.entrypoints=http
      #- traefik.docker.network=traefik-public
      #- traefik.http.routers.web-api.service=web-api
      #- traefik.http.services.api-proxy-livraison-traduction.loadbalaner.server.port=5002
      #- traefik.docker.network=traefik-public

  #Service api_proxy
  web:
    build:
      context: ./front_formulaire/
      dockerfile: Dockerfile
      args:
        VUE_APP_API: ${VUE_APP_API}
        VUE_APP_API_DOMAIN: ${VUE_APP_API_DOMAIN}
        VUE_APP_API_CLIENT_ID: ${VUE_APP_API_CLIENT_ID}
        VUE_APP_API_AUDIENCE: ${VUE_APP_API_AUDIENCE}
    #Nom du container
    #networks:
      #- traefik-public
    container_name: web
    #network_mode: host
    #Expose le port 8080 de l'host vers le 80 du container
    # ports:
    #  - "8080:80"
    #Execute d'abord l'api le proxy
    #depends_on:
    #  - api_proxy
    #Définis le réseau
    #Permet de mettre les variable d'environnement
    #environment:
    #- VUE_APP_API=mdr
    labels:
      - traefik.http.routers.web-livraison-traduction.rule=Host(`trad.dan.ynovaix.com`)
      - traefik.enable=true
      #- traefik.http.routers.web-livraison-traduction.entrypoints=http
      #- traefik.docker.network=traefik
      #- traefik.http.routers.web-livraison-traduction.service=web-livraison-traduction
      #- traefik.http.services.web-livraison-traduction.loadbalaner.server.port=80
      #- traefik.docker.network=traefik-public



#Définis le réseau
#networks:
#  app:
#  traefik-public:
#    external: true
